(function(){var f=true,g=null,h=false,j=navigator,aa=undefined,ba=encodeURIComponent,k=parseInt,l=document,ca=decodeURIComponent,n=Math;function da(a,b){return a.toString=b}function ea(a,b){return a.width=b}function fa(a,b){return a.height=b}
var ga="appendChild",o="push",p="toString",q="valueOf",s="length",ha="plugins",t="prototype",u="width",ia="round",w="slice",x="replace",y="document",z="split",ja="floor",ka="cookie",la="charAt",A="userAgent",B="screen",C="indexOf",ma="body",na="domain",D="write",oa="call",pa="opera",qa="random",ra="createElement",E="getParameter",sa="referrer",F="substring",ta="name",ua="contentWindow",H="height",va="getTime",I="join",wa="getElementsByTagName",ya="toLowerCase",J=this,za=function(a,b,c){a=a[z](".");
c=c||J;!(a[0]in c)&&c.execScript&&c.execScript("var "+a[0]);for(var d;a[s]&&(d=a.shift());)if(!a[s]&&b!==aa)c[d]=b;else c=c[d]?c[d]:(c[d]={})};n[ja](n[qa]()*2147483648)[p](36);
var Aa=function(a,b){var c=b||J;if(arguments[s]>2){var d=Array[t][w][oa](arguments,2);return function(){var e=Array[t][w][oa](arguments);Array[t].unshift.apply(e,d);return a.apply(c,e)}}else return function(){return a.apply(c,arguments)}},Ba=Date.now||function(){return+new Date},K=function(a,b,c){za(a,b,c)},Ca=function(a,b){function c(){}c.prototype=b[t];a.ra=b[t];a.prototype=new c};var L=function(a,b){ea(this,a);fa(this,b)};da(L[t],function(){return"("+this[u]+" x "+this[H]+")"});L[t].floor=function(){ea(this,n[ja](this[u]));fa(this,n[ja](this[H]));return this};L[t].round=function(){ea(this,n[ia](this[u]));fa(this,n[ia](this[H]));return this};var Da=function(a){return a[x](/^[\s\xa0]+|[\s\xa0]+$/g,"")},Ga=function(a){if(a[C]("&")!=-1)return"document"in J&&a[C]("<")==-1?Ea(a):Fa(a);return a},Ea=function(a){var b=J[y][ra]("a");b.innerHTML=a;b.normalize&&b.normalize();a=b.firstChild.nodeValue;b.innerHTML="";return a},Fa=function(a){return a[x](/&([^;]+);/g,function(b,c){switch(c){case "amp":return"&";case "lt":return"<";case "gt":return">";case "quot":return'"';default:if(c[la](0)=="#"){c=Number("0"+c.substr(1));if(!isNaN(c))return String.fromCharCode(c)}return b}})},
Ia=function(a,b){var c=0;a=Da(String(a))[z](".");b=Da(String(b))[z](".");for(var d=n.max(a[s],b[s]),e=0;c==0&&e<d;e++){var i=a[e]||"",m=b[e]||"",r=new RegExp("(\\d*)(\\D*)","g"),v=new RegExp("(\\d*)(\\D*)","g");do{var N=r.exec(i)||["","",""],G=v.exec(m)||["","",""];if(N[0][s]==0&&G[0][s]==0)break;c=N[1][s]==0?0:k(N[1],10);var xa=G[1][s]==0?0:k(G[1],10);c=Ha(c,xa)||Ha(N[2][s]==0,G[2][s]==0)||Ha(N[2],G[2])}while(c==0)}return c},Ha=function(a,b){if(a<b)return-1;else if(a>b)return 1;return 0};Ba();var Ja,Ka,La,Ma,Na,Oa,Pa,Qa,Ra,Sa=function(){return J.navigator?J.navigator[A]:g},Ta=function(){return J.navigator},Ua=function(){Na=Ma=La=Ka=Ja=h;var a;if(a=Sa()){var b=Ta();Ja=a[C]("Opera")==0;Ka=!Ja&&a[C]("MSIE")!=-1;Ma=(La=!Ja&&a[C]("WebKit")!=-1)&&a[C]("Mobile")!=-1;Na=!Ja&&!La&&b.product=="Gecko"}};Ua();
var Va=Ja,Wa=Ka,Xa=Na,Ya=La,Za=Ma,$a=function(){var a=Ta();return a&&a.platform||""},ab=$a(),bb=function(){Oa=ab[C]("Mac")!=-1;Pa=ab[C]("Win")!=-1;Qa=ab[C]("Linux")!=-1;Ra=!!Ta()&&(Ta().appVersion||"")[C]("X11")!=-1};bb();
var cb=function(){var a="",b;if(Va&&J[pa]){a=J[pa].version;a=typeof a=="function"?a():a}else{if(Xa)b=/rv\:([^\);]+)(\)|;)/;else if(Wa)b=/MSIE\s+([^\);]+)(\)|;)/;else if(Ya)b=/WebKit\/(\S+)/;if(b)a=(a=b.exec(Sa()))?a[1]:""}return a},db=cb(),eb={},fb=function(a){return eb[a]||(eb[a]=Ia(db,a)>=0)};var gb=function(a){var b=a[y];if(Ya&&!fb("500")&&!Za){if(typeof a.innerHeight=="undefined")a=window;b=a.innerHeight;var c=a[y].documentElement.scrollHeight;if(a==a.top)if(c<b)b-=15;return new L(a.innerWidth,b)}a=b.compatMode=="CSS1Compat"&&(!Va||Va&&fb("9.50"))?b.documentElement:b[ma];return new L(a.clientWidth,a.clientHeight)};Ya&&fb("522");function hb(a,b){a=parseFloat(a);return isNaN(a)||a>1||a<0?b:a}function ib(a,b){if(a=="true")return f;if(a=="false")return h;return b}function jb(a,b){var c=/^([\w-]+\.)+[\w-]{2,}(\:[0-9]+)?$/;return c.test(a)?a:b};var kb=ib("false",h),lb=window;var nb="pagead2.googlesyndication.com",ob="googleads.g.doubleclick.net",pb="pubads.g.doubleclick.net",qb="securepubads.g.doubleclick.net",rb="partner.googleadservices.com",sb=jb("pagead2.googlesyndication.com",nb);jb("googleads.g.doubleclick.net",ob);jb("pagead2.googlesyndication.com",nb);var tb=jb("pubads.g.doubleclick.net",pb),ub=jb("partner.googleadservices.com",rb),vb=jb("securepubads.g.doubleclick.net",qb);function M(a){return typeof ba=="function"?ba(a):escape(a)}function wb(a,b,c){var d=l[ra]("script");d.type="text/javascript";if(b)d.onload=b;if(c)d.id=c;d.src=a;var e=l[wa]("head")[0];if(!e)return h;window.setTimeout(function(){e[ga](d)},0);return f}function xb(a){if(a in yb)return yb[a];return yb[a]=j[A][ya]()[C](a)!=-1}var yb={};function zb(){return xb("msie")&&!window[pa]}
function Ab(){if(j[ha]&&j.mimeTypes[s]){var a=j[ha]["Shockwave Flash"];if(a&&a.description)return a.description[x](/([a-zA-Z]|\s)+/,"")[x](/(\s)+r/,".")}else if(j[A]&&j[A][C]("Windows CE")>=0){a=3;for(var b=1;b;)try{b=new ActiveXObject("ShockwaveFlash.ShockwaveFlash."+(a+1));a++}catch(c){b=g}return a[p]()}else if(zb()){b=g;try{b=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.7")}catch(d){a=0;try{b=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.6");a=6;b.AllowScriptAccess="always"}catch(e){if(a==
6)return a[p]()}try{b=new ActiveXObject("ShockwaveFlash.ShockwaveFlash")}catch(i){}}if(b){a=b.GetVariable("$version")[z](" ")[1];return a[x](/,/g,".")}}return"0"}function Bb(a,b){var c=n[qa]();if(c<b){b=n[ja](c/b*a[s]);return a[b]}return""}
var Cb=function(a){a.u_tz=-(new Date).getTimezoneOffset();a.u_his=window.history[s];a.u_java=j.javaEnabled();if(window[B]){a.u_h=window[B][H];a.u_w=window[B][u];a.u_ah=window[B].availHeight;a.u_aw=window[B].availWidth;a.u_cd=window[B].colorDepth}if(j[ha])a.u_nplug=j[ha][s];if(j.mimeTypes)a.u_nmime=j.mimeTypes[s]},Db=function(a){var b=lb;if(a&&b.top!=b)b=b.top;try{return b[y]&&!b[y][ma]?new L(-1,-1):gb(b||window)}catch(c){return new L(-12245933,-12245933)}},Eb=function(a,b){var c=a[s];if(c==0)return 0;
b=b||305419896;for(var d=0;d<c;d++){var e=a.charCodeAt(d);b^=(b<<5)+(b>>2)+e&4294967295}return b},Gb=function(a){if(a==a.top)return 0;var b=[];b[o](l.URL);a[ta]&&b[o](a[ta]);a=f;a=Db(!a);b[o](a[u][p]());b[o](a[H][p]());b=Eb(b[I](""));return b>0?b:4294967296+b};var Hb={google_ad_channel:"channel",google_ad_host:"host",google_ad_host_channel:"h_ch",google_ad_host_tier_id:"ht_id",google_ad_section:"region",google_ad_type:"ad_type",google_adtest:"adtest",google_allow_expandable_ads:"ea",google_alternate_ad_url:"alternate_ad_url",google_alternate_color:"alt_color",google_bid:"bid",google_city:"gcs",google_color_bg:"color_bg",google_color_border:"color_border",google_color_line:"color_line",google_color_link:"color_link",google_color_text:"color_text",google_color_url:"color_url",
google_contents:"contents",google_country:"gl",google_cust_age:"cust_age",google_cust_ch:"cust_ch",google_cust_gender:"cust_gender",google_cust_id:"cust_id",google_cust_interests:"cust_interests",google_cust_job:"cust_job",google_cust_l:"cust_l",google_cust_lh:"cust_lh",google_cust_u_url:"cust_u_url",google_disable_video_autoplay:"disable_video_autoplay",google_ed:"ed",google_encoding:"oe",google_feedback:"feedback_link",google_flash_version:"flash",google_font_face:"f",google_font_size:"fs",google_hints:"hints",
google_kw:"kw",google_kw_type:"kw_type",google_language:"hl",google_page_url:"url",google_region:"gr",google_reuse_colors:"reuse_colors",google_safe:"adsafe",google_tag_info:"gut",google_targeting:"targeting",google_ui_features:"ui",google_ui_version:"uiv",google_video_doc_id:"video_doc_id",google_video_product_type:"video_product_type"},Ib={google_ad_client:"client",google_ad_format:"format",google_ad_output:"output",google_ad_callback:"callback",google_ad_height:"h",google_ad_override:"google_ad_override",
google_ad_slot:"slotname",google_ad_width:"w",google_ctr_threshold:"ctr_t",google_image_size:"image_size",google_last_modified_time:"lmt",google_max_num_ads:"num_ads",google_max_radlink_len:"max_radlink_len",google_num_radlinks:"num_radlinks",google_num_radlinks_per_unit:"num_radlinks_per_unit",google_only_ads_with_video:"only_ads_with_video",google_rl_dest_url:"rl_dest_url",google_rl_filtering:"rl_filtering",google_rl_mode:"rl_mode",google_rt:"rt",google_skip:"skip"},Jb={google_only_pyv_ads:"pyv",
google_with_pyv_ads:"withpyv"};var Kb=l,O=j,P=window;
function Lb(){var a=Kb[ka],b=n[ia]((new Date)[va]()/1E3),c=P.google_analytics_domain_name;c=typeof c=="undefined"?Mb("auto"):Mb(c);var d=a[C]("__utma="+c+".")>-1,e=a[C]("__utmb="+c)>-1,i=a[C]("__utmc="+c)>-1,m={},r=!!P&&!!P.gaGlobal;if(d){a=a[z]("__utma="+c+".")[1][z](";")[0][z](".");m.sid=e&&i?a[3]+"":r&&P.gaGlobal.sid?P.gaGlobal.sid:b+"";m.vid=a[0]+"."+a[1];m.from_cookie=f}else{m.sid=r&&P.gaGlobal.sid?P.gaGlobal.sid:b+"";m.vid=r&&P.gaGlobal.vid?P.gaGlobal.vid:(n[ia](n[qa]()*2147483647)^Nb()&2147483647)+
"."+b;m.from_cookie=h}m.dh=c;m.hid=r&&P.gaGlobal.hid?P.gaGlobal.hid:n[ia](n[qa]()*2147483647);return P.gaGlobal=m}function Nb(){var a=Kb[ka]?Kb[ka]:"",b=P.history[s],c,d=[O.appName,O.version,O.language?O.language:O.browserLanguage,O.platform,O[A],O.javaEnabled()?1:0][I]("");if(P[B])d+=P[B][u]+"x"+P[B][H]+P[B].colorDepth;else if(P.java){c=java.awt.Toolkit.getDefaultToolkit().getScreenSize();d+=c[B][u]+"x"+c[B][H]}d+=a;d+=Kb[sa]?Kb[sa]:"";for(a=d[s];b>0;)d+=b--^a++;return Ob(d)}
function Ob(a){var b=1,c=0,d;if(!(a==aa||a=="")){b=0;for(d=a[s]-1;d>=0;d--){c=a.charCodeAt(d);b=(b<<6&268435455)+c+(c<<14);c=b&266338304;b=c!=0?b^c>>21:b}}return b}function Mb(a){if(!a||a==""||a=="none")return 1;if("auto"==a){a=Kb[na];if("www."==a[F](0,4))a=a[F](4,a[s])}return Ob(a[ya]())};function Pb(a,b,c,d){this._value_=a;this._expires_=b;this._path_=c;this._domain_=d;if(!this._path_)this._path_="/";if(this._domain_==g)this._domain_=l[na]}da(Pb[t],function(){return"[GA_GoogleCookieInfo: value="+this._value_+", expires="+this._expires_+", path="+this._path_+"]"});function Qb(){this.v=Rb(this);this.N=h;if(!this.v)this.N=Sb(this)}Qb[t].M="__gads=";Qb[t].B="GoogleAdServingTest=";Qb[t].setCookieInfo=function(a){this.q=a._cookies_[0];if(this.q!=g){this.v=this.q._value_;Tb(this)}};
var Ub=function(a,b){a=(new Date)[q]();var c=new Date;c.setTime(a+b);return c},Vb=function(a){var b=15552E6;a=Ub(a,b);b="ID=12345:T="+b;var c="/",d=l[na];return new Pb(b,a[q](),c,d)},Wb="http://"+ub+"/gampad/cookie.js?callback=_GA_googleCookieHelper.setCookieInfo",Xb=function(a,b){if(!(a.v||!a.N)){a="script";var c=l[na];b=Wb+"&client="+M(b)+"&domain="+M(c);l[D]("<"+a+' src="'+b+'"></'+a+">")}},Sb=function(a){l.cookie=a.B+"Good";var b=Yb(a,a.B);if(b=b=="Good"){var c=Ub(a,-1);l.cookie=a.B+"; expires="+
c.toGMTString()}return b},Rb=function(a){return a=Yb(a,a.M)},Yb=function(a,b){a=l[ka];var c=a[C](b),d="";if(c!=-1){b=c+b[s];c=a[C](";",b);if(c==-1)c=a[s];d=a[F](b,c)}return d},Tb=function(a){if(a.q!=g)if(a.v){var b=new Date;b.setTime(1E3*a.q._expires_);var c=a.q._domain_;a=a.M+a.v+"; expires="+b.toGMTString()+"; path="+a.q._path_+"; domain=."+c;l.cookie=a}};var Q=function(a){this.ga=a;this.T=[];this.S=0;this.G=[];this.aa=0;this.L=[];this.$=h;this.f=this.X="";this.Z=h},Zb=function(a,b,c){var d=a.ga[c],e=a.T;a.ga[c]=function(i){if(i&&i[s]>0){var m=i[s]>1?i[1].url:g;e[o]([b,Ga(i[0].url),m])}d(i)}},$b=function(a){a.S++},ac=function(a,b){a.G[o](b)},bc=function(a){if(!a.$){wb("http://"+sb+"/pagead/osd.js");a.$=f}},cc=function(a,b){if(a.S>0){var c=l[wa]("iframe");a=a.Z?"google_ads_iframe_":"google_ads_frame";for(var d=0;d<c[s];d++){var e=c.item(d);e.src&&e[ta]&&
e[ta][C](a)==0&&b(e,e.src)}}},dc=function(a,b){a=a.T;if(a[s]>0)for(var c=l[wa]("a"),d=0;d<c[s];d++)for(var e=0;e<a[s];e++)if(c.item(d).href==a[e][1]){var i=c.item(d).parentNode;if(a[e][2])for(var m=i,r=0;r<4;r++){if(m.innerHTML[C](a[e][2])>0){i=m;break}m=m.parentNode}b(i,a[e][0]);a.splice(e,1);break}},fc=function(a,b){for(var c=0;c<a.G[s];c++){var d=a.G[c],e=ec(d);if(e)(e=l.getElementById("google_ads_div_"+e))&&b(e,d)}};Q[t].Q=function(a){dc(this,a);fc(this,a);cc(this,a)};
Q[t].setupOsd=function(a,b,c){this.aa=a;this.X=b;this.f=c};Q[t].getOsdMode=function(){return this.aa};Q[t].getEid=function(){return this.X};Q[t].getCorrelator=function(){return this.f};Q[t].R=function(){return this.T[s]+this.S+this.G[s]};Q[t].setValidAdBlockTypes=function(a){this.L=a};
Q[t].registerAdBlockByType=function(a,b,c){if(this.L[s]>0){for(var d=0;d<this.L[s];d++)if(this.L[d]==a){this.Z=c;if(a=="js")Zb(this,b,"google_ad_request_done");else if(a=="html")$b(this);else a=="json_html"&&ac(this,b)}bc(this)}};var ec=function(a){if((a=a.match(/[&\?](?:slotname)=([^&]+)/))&&a[s]==2)return a[1];return""},gc=function(){window.__google_ad_urls||(window.__google_ad_urls=new Q(window));return window.__google_ad_urls};K("Goog_AdSense_getAdAdapterInstance",gc);
K("Goog_AdSense_OsdAdapter",Q);K("Goog_AdSense_OsdAdapter.prototype.numBlocks",Q[t].R);K("Goog_AdSense_OsdAdapter.prototype.findBlocks",Q[t].Q);K("Goog_AdSense_OsdAdapter.prototype.getOsdMode",Q[t].getOsdMode);K("Goog_AdSense_OsdAdapter.prototype.getEid",Q[t].getEid);K("Goog_AdSense_OsdAdapter.prototype.getCorrelator",Q[t].getCorrelator);K("Goog_AdSense_OsdAdapter.prototype.setValidAdBlockTypes",Q.setValidAdBlockTypes);K("Goog_AdSense_OsdAdapter.prototype.setupOsd",Q[t].setupOsd);
K("Goog_AdSense_OsdAdapter.prototype.registerAdBlockByType",Q[t].registerAdBlockByType);function hc(a,b){try{return a.top[y].URL==b.URL}catch(c){}return h};var ic=/^(?:([^:\/?#]+):)?(?:\/\/(?:([^\/?#]*)@)?([^\/?#:@]*)(?::([0-9]+))?)?([^?#]+)?(?:\?([^#]*))?(?:#(.*))?$/,jc=function(a){return a&&ca(a)};var kc=function(a){this.fa=(this.O=a&&a.GA_jstiming)&&this.O.load};kc[t].tick=function(a,b){this.fa.tick(a,b)};kc[t].report=function(a){var b={};b.e=a;this.O.report(this.fa,b)};var lc=function(){};Ca(lc,kc);lc[t].tick=function(){};lc[t].report=function(){};var mc=function(a,b,c,d){if(c<=4){b=b+"_"+c;d?a.tick(b,d+"_"+c):a.tick(b)}};var R=lb&&n[qa]()<hb("0.005",0.0010)&&lb.GA_jstiming&&lb.GA_jstiming.load&&lb.location.protocol=="http:"?new kc(lb):new lc(lb);R.tick("js_load");function S(a){return typeof a=="function"}function nc(a,b){if(typeof a!="string"||a[s]==0)return g;else if(typeof b!="string"||b[s]==0)return g;return oc(T(),a,b)}K("GA_googleAddSlot",nc);function _GA_googleInitializeAdEngine(a){if(!U()){pc(qc(a));rc(U())}}K("_GA_googleInitializeAdEngine",_GA_googleInitializeAdEngine);
function sc(){T().ha=f;_GA_googleInitializeAdEngine(g);var a=U().g;a=="sync"||a=="sync_sra"?U().j():tc(T())}K("GA_googleFetchAds",sc);function uc(){_GA_googleInitializeAdEngine("iframe");Xb(window._GA_googleCookieHelper,window.GS_googleGetIdsForAdSenseService())}K("GA_googleUseIframeRendering",uc);function vc(){var a=window.GA_googleEnv[E]("google_ad_impl");a==g&&window.GA_googleEnv.setParameter("google_ad_impl","sync_sra")}K("GA_googleUseSyncSRARendering",vc);
function wc(a){window.GA_googleEnv.setParameter("google_domain_reset_url",a)}K("GA_googleDomainResetUrl",wc);function xc(a){if(U()!=g)if(U().g!="iframe"){if(yc(U()))if(U().K){var b=zc(T(),a);if(b==g)return;else if(!b._enabled_)return}else return;else if(Ac(U(),a)!=g&&!U().l)return;U().n(a)}}K("GA_googleFillSlot",xc);function Bc(a,b,c,d){a=a||"";b=b||"";c=c||0;d=d||0;if(U()!=g)if(U().g=="iframe"){oc(T(),a,b);a=new Cc(c,d,h,f);Dc(T(),b,a);U().n(b)}}K("GA_googleFillSlotWithSize",Bc);
function Ec(){Fc(new Gc(Hb));pc(g)}K("GA_googleResetAll",Ec);window.google_noFetch=h;function Hc(){window.google_noFetch=f}K("GA_googleNoFetch",Hc);function Ic(){window.google_delayFetch=f}K("GA_googleDelayFetch",Ic);function Cc(a,b,c,d){this._width_=a;this._height_=b;this._expandable_=c;this._enabled_=d}da(Cc[t],function(){return"[GA_GoogleAdSlotAttr: width="+this._width_+", height="+this._height_+", expandable="+this._expandable_+", enabled="+this._enabled_+"]"});
function Jc(a){var b={};a=a[z]("?");a=a[a[s]-1][z]("&");for(var c=0;c<a[s];c++){var d=a[c][z]("=");if(d[0])try{b[d[0][ya]()]=d[s]>1?window.decodeURIComponent?ca(d[1][x](Kc," ")):unescape(d[1]):""}catch(e){}}return b}function Lc(a){a=a||l.URL;this.da=Jc(a)}Lc[t].getParameter=function(a){return a==g?g:this.da[a]};Lc[t].setParameter=function(a,b){this.da[a]=b};var Mc=function(){if(!kb)return"http://"+tb;return"https://"+vb};
function Nc(a){return a[x](/&/g,"&amp;")[x](/</g,"&lt;")[x](/>/g,"&gt;")[x](/\"/g,"&quot;")}function Oc(){this.D=g;this.ea=h;this.qa=(new Date)[q]()}
var Qc=function(a,b){if(a.D==g)if(!a.ea){a.D=window.open("","GoogleAdCapture","width=1100, height=1400, status=no, resizable=yes, scrollbars=yes,menubar=yes, toolbar=yes");if(a.D){var c=a.D[y],d=[];d[o]('<html>\n<head>\n<title>Google Ad Capture Window</title>\n<script>function displayTime(id, start){var delta=(new Date()).valueOf() - start;document.getElementById(id).innerHTML=""+delta;}var pageStartTime = (new Date()).valueOf();var slotStartTime = 0;window.onload=function(){displayTime("total", pageStartTime);};<\/script></head>\n<body>\n');d[o]("<p>Google Ad Capture Window</p>");
for(var e in b)S(b[e])||d[o](Pc(a,e,b[e]));d[o]("<p>Time blocked rendering ads (ms): <label id='blocked'></label>");d[o]("<script>displayTime('blocked', pageStartTime);<\/script>");d[o]("<p>Total Page Load Time (ms): <label id='total'></label>");d[o]("</body>\n</html>");a=d[I]("\n");(b=window.GA_googleEnv[E]("google_capture_norender")!=g)?c[D](Nc(a)):c[D](a);c.close()}else a.ea=f}},Pc=function(a,b,c){a="<script>slotStartTime = (new Date()).valueOf();<\/script>";var d="<p>Slot "+b+"</p>";c=c==g||c._html_==
g?"No ad":c._html_;var e="<p>Slot Time (ms): <label id='"+b+"'></label>";b='<script>displayTime("'+b+'", slotStartTime);<\/script>';return a+d+"\n"+c+"\n"+e+b};function Rc(a){this.d={};this.C=a}var Sc=function(a,b,c,d){if(b){c||(c="");if(b=="google_gl")b="google_country";else if(b=="google_region")b="google_section";if(b in a.C)if((d=typeof d=="undefined"||d)||!a.d[b])a.d[b]=c}},Tc=function(a,b){for(var c in b.d)S(b.d[c])||a.d[c]||(a.d[c]=b.d[c])};Rc[t].getAttribute=function(a){return this.d[a]};
Rc[t].h=function(){var a=[];for(var b in this.d)if(!S(this.d[b])){var c=Hb[b]||Ib[b]||Jb[b]||g,d=this.d[b];c&&d&&a[o](c+"="+M(d))}return a[I]("&")};
var Vc=function(a,b,c,d){a=Uc(a,b,c,d);b=[];a[0]&&a[0][s]>0&&b[o](a[0][I]("&"));a[1]&&a[1][s]>0&&b[o]("sps="+a[1][I]("|"));return b[I]("&")},Uc=function(a,b,c,d){var e=[],i=[];b=b.d;for(var m in d)if(!S(m)){var r=d[m];if(r){var v="";if(b[m]!=g)v=M(b[m]);var N=[],G=-1,xa=-1;for(var mb in a)if(!S(a[mb])){++G;if(c[mb]==g)N[o]("");else{var Fb=c[mb].d;if(Fb[m]!=g){N[o](M(M(Fb[m])));xa=G}else N[o]("")}}if(xa>=0){G=M(v);v=[];v[o](G);for(G=0;G<=xa;++G)v[o](N[G]);i[o](r+","+v[I](","))}else v&&e[o](r+"="+v)}}a=
[];a[o](e);a[o](i);return a};function Wc(a,b){this.J=a;this.s=b;this.V=0;this.na=this.P=this.U=h;this.la=this.ma=this.Y=this.ia=g}var Xc=function(a){a.P=f;a.ia=(new Date)[q]()},Yc=function(a){a.Y=(new Date)[q]()},Zc=function(a){a.na=f;a.ma=(new Date)[q]()},$c=function(a){a.la=(new Date)[q]()};da(Wc[t],function(){return"[GA_GoogleAdSlot: pubid="+this.J+", name="+this.s+", loaded="+this.U+", tries="+this.V+"]"});
function Gc(a){this.a={};this.c=[];this.r={};this.C=a;this.ca=new Rc(this.C);this.A={};this.ha=h;this.o=g}
var oc=function(a,b,c){b=new Wc(b,c);return a.a[b.s]=b},ad=function(a,b){var c=[];for(var d in a.a)if(!S(a.a[d])){if(b){var e=zc(a,d);if(e==g||!e._enabled_)continue}e=a.a[d];e.P||c[o](e)}return c},bd=function(a,b){return ad(a,b)[s]},cd=function(a){var b=[];for(var c in a.a){var d=a.a[c];S(d)||d.P&&d.Y==g&&b[o](c)}return b},dd=function(a){var b=0;for(var c in a.a)if(!S(a.a[c])){var d=zc(a,c);d!=g&&d._enabled_&&b++}return b},ed=function(a){for(var b in a.a)if(!S(a.a[b])){var c=a.a[b];Xc(c)}},fd=function(a,
b){a=a.a[b];Xc(a)},gd=function(a,b){a=a.a[b];Yc(a)},hd=function(a,b){a=a.a[b];Zc(a)},id=function(a,b){b=a.a[b];$c(b);mc(R,"ga_render",a.c[s],"ga_srt")},jd=function(a){var b=0;for(var c in a.a)S(a.a[c])||b++;return b};da(Gc[t],function(){var a="[AdData:",b=[];for(var c in this.a)S(this.a[c])||b[o](this.a[c][p]());for(var d in this.r)S(this.r[d])||b[o]("["+d+","+this.r[d]+"]");a+=b[I]();a+="]";return a});
var kd=function(a,b){return a.a[b]},ld=function(a,b,c){if(!(b==g||b[s]==0)){if(c==g||c[s]==0)c="";var d=a.r[b];a.r[b]=d==g?c:d+","+c}};function md(a,b){ld(T(),a,b)}K("GA_googleAddAttr",md);var nd=function(a,b,c){Sc(a.ca,b,c)};function od(a,b){nd(T(),a,b)}K("GA_googleAddAdSensePageAttr",od);var pd=function(a){return a.ca},qd=function(a,b,c,d){if(!(b==g||b[s]==0)){if(U()==g||U().g!="iframe"){var e=a.a[b];if(e==g)return}e=a.A[b];if(e==g)a.A[b]=new Rc(a.C);Sc(a.A[b],c,d)}};
function rd(a,b,c){qd(T(),a,b,c)}K("GA_googleAddAdSenseSlotAttr",rd);var sd=function(a,b){return a.A[b]},td=function(){var a=Mc();return a+"/gampad/slotdata.js?callback=GA_googleSetAdSlotAttributes"},tc=function(a){if(a.o!=g)U().j();else{var b=[];for(var c in a.a)S(a.a[c])||b[o](c);a=window.GS_googleGetIdsForAdSenseService();b=td(window)+"&client="+escape(a)+"&page_slots="+escape(b[I]());l[D]("<script src = '"+b+"'><\/script>")}};Gc[t].setAdSlotAttributes=function(a){this.o=a;U().K=f;U().j()};
function ud(a){T().setAdSlotAttributes(a)}K("GA_googleSetAdSlotAttributes",ud);var Dc=function(a,b,c){if(a.o==g)a.o={};a.o[b]=c;U().K=f},zc=function(a,b){return a.o!=g?a.o[b]:g};function vd(a,b,c){if(!c||c<0||c>1)c=0;this.oa=n[qa]()<c;this.ja=a;this.W=b+"/pagead/gen_204?id="+M(a);this.ka=[]}
var V=function(a,b,c){if(b&&b.match(/^\w+$/)&&c)a.W+="&"+b+"="+M(c)},wd=function(a){var b=T();for(var c in b.a){var d=b.a[c];if(!S(d)&&d.J!=g){V(a,"pub_id",d.J);break}}V(a,"nslots",jd(b)[p]());V(a,"pub_url",l.URL);V(a,"pub_ref",l[sa])},xd=function(a){if(!a.oa||!a.ja||!a.W)return h;var b=new Image;b.src=a.W;a.ka[o](b);return f};function W(a){this.i=g;this.o={};this.p=this.b="";this.l=a;this.m=this.I=this.t=h;this.g="sync";this.pa=Hb;this.u=f;this.K=h}
var rc=function(a){a.t=window.GA_googleEnv[E]("google_nofetch")!=g||window.google_noFetch;a.I=window.GA_googleEnv[E]("google_norender")!=g;a.m=window.GA_googleEnv[E]("google_capture")!=g||window.GA_googleEnv[E]("google_capture_norender")!=g;if(a.m)a.I=f;yd(a,window);a.b=a.p;var b=Aa(a.ba,a);zd(a,window,b)},zd=function(a,b,c){if(b.attachEvent){b.attachEvent("onload",c);return f}if(b.addEventListener){b.addEventListener("load",c,h);return f}return h};
W[t].F=function(){this.m&&Qc(window.GA_googleAdCapture,this.i)};
var Ad=function(a){if(a.g=="sync_sra"){var b=T(),c=jd(b);b=b.c[s];if(c!=b){a.H=new vd("sra_mismatch",Mc(),hb("0.001",0.0010));V(a.H,"correlator",a.f);V(a.H,"fslots",b[p]());wd(a.H);xd(a.H)}}},Bd=function(a){R.tick("ga_onload");R.report(a.g)},Cd=function(a){var b=cd(T());if(b[s]>0){a.z=new vd("missing_cb",Mc(),hb("0.01",0.0010));V(a.z,"pending",b[I]());V(a.z,"correlator",a.f);V(a.z,"impl",a.g);wd(a.z);xd(a.z)}};
W[t].ba=function(){Bd(this);this.F();Ad(this);Cd(this)};var yd=function(a){var b=window.GA_googleEnv[E]("google_ad_url");if(b==g||b[s]==0)a.p=Mc()+"/gampad/ads?";else{if(b[la](b[s]-1)!="?")b+="?";a.p=b}};W[t].k=function(){};
var Ac=function(a,b){return a.i!=g?a.i[b]:g},Dd=function(){var a=j[A],b=a[C]("MSIE ");return b==-1?0:parseFloat(a[F](b+5,a[C](";",b)))},Kc=/\+/g,Ed=function(a,b){b=b[ya]();if(b[F](0,3)!="ca-")b="ca-"+b;return b},Y=function(a,b,c){c!=g&&X(a,b,M(c[p]()))},X=function(a,b,c){if(c!=g&&c!="")a.b+=a.b[la](a.b[s]-1)!="?"?"&"+b+"="+c:b+"="+c},Fd=function(a,b){for(var c=ad(T(),a.u),d=[],e=[],i=[],m=c[s],r=0;r<m;r++){var v=c[r];i[o](v.s);if(!(b!=g&&b!=v.s)){d[o](v.s);e[o](Ed(a,v.J))}}Y(a,"client",e[0]);if(a.l)i[s]>
0&&Y(a,"page_slots",i[I]());else{Y(a,"slotname",d[I]());T().c[s]>0&&Y(a,"page_slots",T().c[I]())}},Gd=function(a,b,c){if(c!=g){a=b.lastIndexOf("?");a=b[C]("google_preview=",a);c=b[C]("&",a);if(c==-1){c=b[s]-1;a-=1}return b[F](0,a)+b[F](c+1,b[s])}return b},Hd=function(a,b,c){if(hc(b,c))return c.URL;return c[sa]},Jd=function(a,b,c){if(Id(a,b,c)!=c.URL)return c[na];return""},Id=function(a,b,c){var d=pd(T()).getAttribute("google_page_url");if(d)return d;return Hd(a,b,c)},Ld=function(a,b,c,d){Y(a,"url",
Gd(a,Id(a,window,l),window.GA_googleEnv[E]("google_preview")));Y(a,"ref",l[sa]);Y(a,"lmt",(Date.parse(l.lastModified)/1E3)[p]());X(a,"dt",b[va]());if(l[ma]){b=l[ma].scrollHeight;var e=l[ma].clientHeight;e&&b&&Y(a,"cc",n[ia](e*100/b)[p]())}b=f;if(b=Db(b)){Y(a,"biw",b[u]);Y(a,"bih",b[H])}b=Kd(window);Y(a,"ifi",b);b=Gb(window);b!=0&&Y(a,"ifk",b[p]());b=window.GA_googleEnv[E]("deb");b!=g&&Y(a,"deb",b);b=window.GA_googleEnv[E]("haonly");b!=g&&Y(a,"haonly",b);b=pd(T());j[A][C]("MSIE ")>0&&Sc(b,"google_encoding",
l.charset,h);e="";if(d)e=Vc(T().a,b,T().A,a.pa);else{c=sd(T(),c);if(c==g)c=b;else Tc(c,b);e=c.h()}if(e)a.b+="&"+e},Md=function(a,b,c){var d=T().r,e=[];for(var i in d)S(d[i])||e[o](M(i)+"="+M(d[i]));Y(a,"cust_params",e[I]("&"));if(b._GA_googleCookieHelper){Y(a,"cookie",b._GA_googleCookieHelper.v);b._GA_googleCookieHelper.N&&Y(a,"cookie_enabled","1")}(b=Jd(a,b,c))&&Y(a,"cdm",b)},Nd=function(a){Lb();var b=window;X(a,"ga_vid",b.gaGlobal.vid);X(a,"ga_sid",b.gaGlobal.sid);X(a,"ga_hid",b.gaGlobal.hid);X(a,
"ga_fc",b.gaGlobal.from_cookie);Y(a,"ga_wpids",b.google_analytics_uacct)},Od=function(a,b){for(var c in b){var d=b[c];S(d)||X(a,c,d)}};
W[t].h=function(a){this.k();var b=Pd(this.f[p]());X(this,"eid",b);b=new Date;Fd(this,a);Md(this,window,l);window.GA_googleEnv[E]("google_preview")!=g&&X(this,"gct",window.GA_googleEnv[E]("google_preview"));Nd(this);Ld(this,b,a,this.l);a={};Cb(a);Od(this,a);X(this,"flash",Ab());this.b=this.b[F](0,2E3);this.b=this.b[x](/%\w?$/,"");a=this.g=="iframe"||this.g=="fallback"?"html":"json_html";gc().registerAdBlockByType(a,this.b,f);return this.b};
var yc=function(a){return a.u},Qd=function(a,b){a=b.getAttribute("id");return a=a.substr(18,a[s]-18)},Rd=function(a,b,c,d,e,i,m){var r="google_ads_iframe_"+b,v=[];if(m){b="google_ads_div_"+b;v[o]("<div id=",b,">")}v[o]("<iframe id=",r," name=",r,' width="',e,'" height="',i,'" vspace="0" hspace="0" allowtransparency="true" ',"scrolling=",a.m?'"auto"':'"no"',' marginwidth="0" marginheight="0" frameborder="0" style="border:0px;"',' src="',Nc(c),'"');d!=g&&v[o](' onload="',d,'"');v[o]("></iframe>");m&&
v[o]("</div>");a=v[I]("");l[D](a)};W[t].createDOMIframe=function(a,b){var c=Ac(this,b),d=c._width_,e=c._height_;c=c._html_;var i=l[ra]("iframe");i.id="google_ads_iframe_"+b;i.name="google_ads_iframe_"+b;ea(i,d);fa(i,e);i.vspace=0;i.hspace=0;i.allowTransparency="true";i.scrolling="no";i.marginWidth=0;i.marginHeight=0;i.frameBorder=0;i.style.border=0;a=l.getElementById(a);a[ga](i);if(this.m){i[ua][y][D](Nc(c));i.scrolling="auto"}else i[ua][y][D](c);i[ua][y].close();id(T(),b)};
function Sd(a,b){U().createDOMIframe(a,b)}K("GA_googleCreateDomIframe",Sd);
var Td=function(){var a=[],b=l[wa]("base");if(b)for(var c=0,d=b[s];c<d;++c){var e=b[c],i=e.getAttribute("target");if(i){a[o]({baseElement:e,originalTagValue:i});e.removeAttribute("target")}}return a},Ud=function(a){if(a)for(var b=0,c=a[s];b<c;++b){var d=a[b];d.baseElement.setAttribute("target",d.originalTagValue)}},Vd=function(a){var b="http://"+sb+"/pagead/inject_object_div.js";if(k(Dd(),10)>6)return h;if(a[C](b)<0)return h;return f},Wd=function(a,b,c){if(a.m)c=Nc(c);a=Td();window.frames[b[ta]].contents=
c;b.src=Vd(c)?'javascript:document.write(window["contents"]);document.close();':'javascript:window["contents"]';Ud(a)},Xd=function(a,b,c){var d=Qd(a,b);try{var e=b[ua]?b[ua][y]:b.contentDocument;if(e==g)if(l.implementation&&l.implementation.createDocument)e=l.implementation.createDocument("",d,g);else if(typeof ActiveXObject!="undefined")e=new ActiveXObject("Msxml.DOMDocument");else return h;e.open("text/html","replace");a.m?e[D](Nc(c)):e[D](c);e.close()}catch(i){return h}return f},Yd=function(a,
b){var c=Qd(a,b),d=kd(T(),c);if(!d.U){d.U=f;d=Ac(a,c);var e=b.parentNode;if(d==g||d._html_==g)e.removeChild(b);else if(d._expandable_)e.innerHTML=d._html_;else d._is_3pas_?Wd(a,b,d._html_):Xd(a,b,d._html_);id(T(),c)}},Zd=function(a,b){var c="google_ads_div_"+b;c="<div id="+c+">";a=Ac(a,b);if(a!=g){c+=a._html_;c+="\n</div>\n";l[D](c);id(T(),b)}},$d=function(a,b){a="google_ads_div_"+b;b="<div id="+a+">";b+="\n</div>\n";l[D](b);return a},ae=function(a){if(!a.u)return f;if(bd(T(),a.u)>0)return f;else if(dd(T())==
0)return h};W[t].setAdContentsBySlot=function(a){mc(R,"ga_srt",T().c[s],"_ga_start");if(this.i==g){this.i=a;for(var b in a)S(a[b])||gd(T(),b)}else for(b in a)if(!S(a[b])){this.i[b]=a[b];gd(T(),b)}var c=h;for(b in a)if(!S(a[b])){var d=a[b];if(c){d._cookies_=[Vb(window._GA_googleCookieHelper)];c=h}d!=g&&d._cookies_!=g&&window._GA_googleCookieHelper.setCookieInfo(d)}};function be(a){U().setAdContentsBySlot(a)}K("GA_googleSetAdContentsBySlot",be);
function Z(a){W[oa](this,a);this.u=h;this.f=(new Date)[va]();this.g=a?"sync_sra":"sync"}Ca(Z,W);Z[t].k=function(){this.b=this.p;Y(this,"correlator",this.f[p]());X(this,"output","json_html");X(this,"callback","GA_googleSetAdContentsBySlotForSync");this.l?X(this,"impl","ss"):X(this,"impl","s");ce(this,T().c);this.l||de(this,T().c,this.i)};
var ce=function(a,b){for(var c=0,d=f,e=0;e<b[s];++e){var i=a.i&&a.i[b[e]];if(i)if(i._is_afc_==aa){d=h;break}else c=2*c+(i._is_afc_?1:0)}d&&X(a,"prev_afc",c)},de=function(a,b,c){if(b&&c){for(var d=[],e=[],i=b[s]-1,m=0;m<i;m++){var r=b[m];if((r=c[r])&&r._cids_&&r._a2ids_){d[o](r._cids_[0]);e[o](r._a2ids_[0])}else{d[o]("");e[o]("")}}if(d[s]>0){b=d[I](",");e=e[I](",");Y(a,"a2ids",e);Y(a,"cids",b)}}},ee=function(a,b){var c=T().a;c=c[b];if(c!=g)if(!a.t){a.h(c.s);fd(T(),b);l[D]("<script src = '"+a.b+"'><\/script>")}};
Z[t].setAdContentsBySlotForSync=function(a){this.setAdContentsBySlot(a);if(this.l)if(T().c[s]==1){a=T().c[0];fe(this,a);return}for(var b in a)S(a[b])||fe(this,b)};function ge(a){U().setAdContentsBySlotForSync(a)}K("GA_googleSetAdContentsBySlotForSync",ge);Z[t].j=function(){ae(this)};var he=function(a){a.h(g);l[D]("<script src = '"+a.b+"'><\/script>");ed(T())};Z[t].n=function(a){T().c[o](a);mc(R,"_ga_start",T().c[s]);if(this.l)T().c[s]==1?he(this):fe(this,a);else ee(this,a)};
var ie=function(a,b,c){if(b.google_js_backfill){a="script";c[D]("<"+a+' src="http://pagead2.googlesyndication.com/pagead/show_ads.js"></'+a+">")}},fe=function(a,b){je(a,window,l,b)},je=function(a,b,c,d){var e=kd(T(),d);if(e!=g){e=Ac(a,d);hd(T(),d);if(e==g||e._empty_){ie(a,b,c,d);id(T(),d)}else if(a.I&&!a.m)id(T(),d);else if(e._snippet_&&!e._is_afc_&&!a.m)Zd(a,d);else if(b.navigator[A][C]("MSIE ")>0){c="GA_googleSyncAdSlotLoaded(this);";var i="about:blank";if(b=b.GA_googleEnv[E]("google_domain_reset_url")){var m=
jc(b.match(ic)[3]||g);if(m===g||m[C](l[na])>=0)i=b}Rd(a,d,i,c,e._width_,e._height_,f)}else{a=$d(a,d);c[D]("<script>GA_googleCreateDomIframe('"+a+"' ,'"+d+"');<\/script>")}}};Z[t].syncAdSlotLoaded=function(a){var b=Qd(this,a);kd(T(),b);Yd(this,a)};function ke(a){U().syncAdSlotLoaded(a)}K("GA_googleSyncAdSlotLoaded",ke);function $(a){W[oa](this,a);this.f=(new Date)[va]();this.g="async"}Ca($,W);
$[t].k=function(){this.b=this.p;le(this);Y(this,"correlator",this.f[p]());X(this,"output","json_html");X(this,"callback","GA_googleSetAdContentsBySlot");X(this,"impl","a")};var le=function(a){a.delay=500;var b=window.GA_googleEnv[E]("google_async_delay");if(b!=g)a.delay=1E3*b};$[t].j=function(){if(ae(this))this.t||window.setTimeout("GA_googleReallyFetchAds();",this.INITIAL_ASYNC_DELAY)};
$[t].reallyFetchAds=function(){if(bd(T(),this.u)!=0){var a=l[wa]("head")[0];if(this.l){var b=l[ra]("script");b.src=this.h(g);a[ga](b);ed(T())}else{var c=T().a;for(var d in c)if(!S(c[d])){b=l[ra]("script");b.src=this.h(d);a[ga](b);fd(T(),d)}}}};function me(){U().reallyFetchAds()}K("GA_googleReallyFetchAds",me);$[t].n=function(a){var b=kd(T(),a);if(b!=g){T().c[o](a);b="GA_googleAsyncAdSlotLoaded(this);";var c=zc(T(),a);Rd(this,a,"about:blank",b,c._width_,c._height_,f)}};
$[t].asyncAdSlotLoaded=function(a){var b=Qd(this,a);kd(T(),b);!this.t&&!this.I&&ne(this,a)};function oe(a){U().asyncAdSlotLoaded(a)}K("GA_googleAsyncAdSlotLoaded",oe);var ne=function(a,b){var c=Qd(a,b),d=kd(T(),c);if(a.i==g||a.i[c]==g){if(!(d.V>30)){window.setTimeout(function(){ne(U(),b)},a.delay);d.V++}}else Yd(a,b)};$[t].F=function(){};function pe(a){W[oa](this,a);this.f=(new Date)[va]();this.g="fallback"}Ca(pe,W);
pe[t].k=function(){this.b=this.p;Y(this,"correlator",this.f[p]());X(this,"output","html");X(this,"impl","fb")};pe[t].j=function(){ae(this)};pe[t].w=function(a){if(this.l){this.h(g);a=this.b+"&currentslot="+M(a)}else a=this.h(a);return a};pe[t].n=function(a){var b=zc(T(),a);if(b!=g){T().c[o](a);if(!this.t){var c=this.w(a);Rd(this,a,c,g,b._width_,b._height_,f)}}};function qe(a){W[oa](this,a);this.f=(new Date)[va]();this.K=f;this.g="iframe"}Ca(qe,W);
qe[t].k=function(){this.b=this.p;Y(this,"correlator",this.f[p]());X(this,"output","html");X(this,"impl","ifr")};qe[t].j=function(){ae(this)};qe[t].w=function(a){if(this.l){this.h(g);a=this.b+"&currentslot="+M(a)}else a=this.h(a);return a};qe[t].n=function(a){var b=zc(T(),a);if(b!=g){T().c[o](a);if(!this.t){var c=this.w(a);Rd(this,a,c,g,b._width_,b._height_,f)}}};
var re=function(){if(zb()){var a=Dd();return a<=5}else if(xb("firefox")){var b=j[A][C]("Firefox")+8;a=k(j[A][la](b),10);b=j[A][w](b);return a<1}else if(xb("safari")){b=j[A][C]("Safari")+7;b=j[A][w](b);a=k(b,10);return a<412}else if(window[pa]!=g){b=j[A][C]("Opera")+6;b=j[A][w](b);a=k(b,10);return a<9}else if(!zb()&&!xb("safari")&&xb("mozilla")){b=j[A][C]("Netscape")+9;b=j[A][w](b);a=k(b,10);return a<7}else return f},se=function(){if(zb()){var a=Dd();return a>5}else if(xb("firefox")){a=j[A][C]("Firefox")+
8;var b=k(j[A][la](a),10);j[A][w](a);return b>1}return h},te=function(){if(re())return"fallback";else if(window.google_delayFetch&&se())return"async";return"sync"},qc=function(a){var b=g;if(typeof a!="undefined"&&a!=g)b=a;else{b=window.GA_googleEnv[E]("google_ad_impl");if(b==g)b=te()}switch(b){case "async":return new $(h);case "sync":return new Z(h);case "sync_sra":return new Z(f);case "fallback":return new pe(h);case "iframe":return new qe(h);default:return new pe(h)}},ue;
function T(){ue||(ue=new Gc(Hb));return ue}function Fc(a){delete ue;ue=a}var ve;function U(){ve||(ve=g);return ve}function pc(a){delete ve;ve=a}if(typeof window.GA_googleEnv=="undefined")window.GA_googleEnv=new Lc;if(typeof window.GA_googleAdCapture=="undefined")window.GA_googleAdCapture=new Oc;if(window._GA_googleCookieHelper==g)window._GA_googleCookieHelper=new Qb(g);function Kd(a){var b="google_unique_id";if(a[b])++a[b];else a[b]=1;return a[b]}
function Pd(a){var b=gc(),c=we(window);if(c!=""){var d=b.getOsdMode();if(c=="36815006"){b.setValidAdBlockTypes(["html","json_html"]);d=1}b.setupOsd(d,c,a)}else c=b.getEid();return c}function we(a){if((a.google_unique_id||0)!=0)return"";return Bb(["36815005","36815006"],hb("0.006",0))}R.tick("js_parse","js_load");R.tick("jl");})()
